apiVersion: v1
kind: LimitRange
metadata:
  name: defaultlimit
  namespace: default
spec:
  limits:
    - type: Container
      default:
        cpu: 100m
        memory: 200Mi
      defaultRequest:
        cpu: 50m
        memory: 160Mi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nsrequest
  namespace: default
spec:
  hard:
    requests.cpu: 150m
    requests.memory: 250Mi
    limits.cpu: 200m
    limits.memory: 300Mi
    pods: 2
