apiVersion: v1
kind: Pod
metadata:
  name: loginapp
  labels:
    app: logiapp
  namespace: test
spec:
  containers:
    - name: loginappp-container
      image: bashadockerhubdemo/loginapp:1
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "200m"
          memory: "200Mi"
        limits:
          cpu: "400m"
          memory: "400Mi"
  imagePullSecrets:
    - name: my-dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: loginapp-service
  namespace: test
spec:
  selector:
    app: logiapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082
