apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: node-js-daemonset
  namespace: staging
spec:
  selector:
    matchLabels:
      app: node-js-app
  template:
    metadata:
      labels:
        app: node-js-app
    spec:
      containers:
        - name: node-js-container
          image: bashadockerhubdemo/node-js-application:1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service 
metadata:
  name: node-js-service
  namespace: staging
spec:
  selector:
    app: node-js-app  
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30085