apiVersion: v1
kind: Namespace
metadata:
  name: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-resource-quota
  namespace: production
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "10Mi"
    limits.cpu: "2"
    limits.memory: "90Mi"
    pods: "2"
