apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  namespace: production
spec:
  selector:
    matchLabels:
      app: login-app1
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: login-app1
    spec:
      containers:
        - name: loginapp-container
          image: bashadockerhubdemo/loginapp:1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "200Mi"
            limits:
              cpu: "400m"
              memory: "400Mi"
          volumeMounts:
            - name: log-volume
              mountPath: /usr/local/tomcat/logs
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: log-volume
          hostPath:
            path: /mnt/d/K8/logfiles
            type: Directory

      imagePullSecrets:
        - name: my-dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: production-redyness-service
  namespace: production
spec:
  selector:
    app: login-app1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30078
