apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
        - name: login-container
          image: bashadockerhubdemo/maven-web-application:2
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "150Mi"
              cpu: "300m"
            requests:
              memory: "150Mi"
              cpu: "300m"
