apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replicationcontroller
  namespace: staging
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: bashadockerhubdemo/maven-web-application:1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service-staging
  namespace: staging
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30083
