apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: spring-pod
  template:
    metadata:
      labels:
        app: spring-pod
    spec:
      containers:
        - name: spring-containers
          image: mithuntechnologies/springboot-mongo-application:1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "20m"
              memory: "150Mi"
            limits:
              cpu: "30m"
              memory: "200Mi"
          env:
            - name: MONGO_DB_HOSTNAME
              value: mongo-service
            - name: MONGO_DB_USERNAME
              value: production
            - name: MONGO_DB_PASSWORD
              value: production@123

---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: spring-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30091

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo-replica
  namespace: default
spec:
  selector:
    matchLabels:
      app: mongo-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-pod
    spec:
      containers:
        - name: mongo-container
          image: mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: "30m"
              memory: "200Mi"
            limits:
              cpu: "50m"
              memory: "250Mi"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: production
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: production@123

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: mongo-pod
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
